import React, { useState } from 'react';
import { HEALTHCARE_REVENUE_CONFIG } from '../data/startupPlanData';
import { 
  HeartHandshake, 
  DollarSign, 
  TrendingUp, 
  ShieldCheck, 
  Users, 
  CheckCircle2, 
  Sparkles, 
  Layers, 
  ArrowRight,
  Info,
  Sliders,
  PiggyBank
} from 'lucide-react';

export const BenefitsHealthcareView: React.FC = () => {
  // Interactive Simulation State
  const [headcount, setHeadcount] = useState<number>(12); // Default to Phase 1 target (12 team members)
  const [survivalGuideSubs, setSurvivalGuideSubs] = useState<number>(12000);
  const [businessManagerSubs, setBusinessManagerSubs] = useState<number>(450);
  const [dineKeySubs, setDineKeySubs] = useState<number>(1200);
  const [commandSuitesSubs, setCommandSuitesSubs] = useState<number>(35);

  // Financial calculations
  const grossMonthlyPremiumPerEmployee = HEALTHCARE_REVENUE_CONFIG.averagePremiumPerEmployeeMonth * HEALTHCARE_REVENUE_CONFIG.dependentMultiplier; // $975/mo
  const totalMonthlyHealthCostAllEmployees = headcount * grossMonthlyPremiumPerEmployee;
  
  // 60% Employer share as mandated
  const employer60PercentShare = totalMonthlyHealthCostAllEmployees * 0.60;
  const employee40PercentShare = totalMonthlyHealthCostAllEmployees * 0.40;

  // Monthly Revenue Generated by live applications
  const survivalGuideMRR = survivalGuideSubs * 4;
  const businessManagerMRR = businessManagerSubs * 32;
  const dineKeyMRR = dineKeySubs * 28;
  const commandSuitesMRR = commandSuitesSubs * 294;

  const totalSaaSMRR = survivalGuideMRR + businessManagerMRR + dineKeyMRR + commandSuitesMRR;

  // Revenue specifically allocated to health escrow based on configured percentages
  const allocatedSurvivalGuide = survivalGuideMRR * 1.0; // 100% allocated to team health & wellness
  const allocatedBusinessManager = businessManagerMRR * 0.50; // 50%
  const allocatedDineKey = dineKeyMRR * 0.40; // 40%
  const allocatedCommandSuites = commandSuitesMRR * 0.25; // 25%

  const totalAllocatedToHealthEscrow = allocatedSurvivalGuide + allocatedBusinessManager + allocatedDineKey + allocatedCommandSuites;

  // Health Care Coverage Metrics
  const coverageRatio = (totalAllocatedToHealthEscrow / employer60PercentShare) * 100;
  const netMonthlyEscrowSurplus = totalAllocatedToHealthEscrow - employer60PercentShare;
  const reserveMonthsAccumulatedPerYear = netMonthlyEscrowSurplus > 0 ? (netMonthlyEscrowSurplus * 12) / employer60PercentShare : 0;

  return (
    <div className="space-y-8 animate-fadeIn">
      {/* Top Banner: The 60% Health Care Coverage Mandate */}
      <div className="p-6 sm:p-8 rounded-2xl bg-gradient-to-br from-[#0B132B] via-emerald-950/20 to-[#0B132B] border-2 border-emerald-500/40 relative overflow-hidden shadow-2xl">
        <div className="absolute top-0 left-0 right-0 h-1.5 bg-emerald-400" />
        <div className="relative z-10 space-y-4">
          <div className="flex flex-wrap items-center justify-between gap-3">
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded bg-emerald-500/15 border border-emerald-500/40 text-emerald-400 font-mono text-xs font-bold">
              <HeartHandshake className="w-4 h-4" />
              SPECIFIC MANDATE: 60% EMPLOYER HEALTH CARE SUBSIDY
            </div>
            <span className="font-mono text-xs text-slate-300 px-2.5 py-1 rounded bg-slate-900 border border-slate-700">
              SaaS Subscription Cash-Flow Matching Engine
            </span>
          </div>

          <div>
            <h1 className="text-2xl sm:text-4xl font-display font-black text-white">
              60% Health Care Coverage via Application Subscriptions
            </h1>
            <p className="text-sm sm:text-base text-slate-300 max-w-3xl mt-2 leading-relaxed">
              Identity AI directly anchors employee wellness to live product success. Recurring subscription revenues from 
              <strong className="text-emerald-300"> IAI Survival Guide ($4/mo)</strong>, 
              <strong className="text-emerald-300"> IAI Business Manager ($32/mo)</strong>, 
              <strong className="text-emerald-300"> DineKey ($28/mo)</strong>, and 
              <strong className="text-emerald-300"> Command Suites ($294/mo)</strong> are routed to cover 
              <strong className="text-[#FF5500]"> 60% of all employee health, dental, and vision insurance premiums</strong>.
            </p>
          </div>

          {/* Quick Metrics Header */}
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 pt-4 border-t border-slate-800/80">
            <div className="p-3 rounded-xl bg-slate-950/90 border border-slate-800">
              <div className="text-[11px] font-mono text-slate-400">TARGET COVERAGE RATE</div>
              <div className="text-2xl font-bold font-display text-emerald-400">60.0%</div>
              <div className="text-[10px] font-mono text-slate-400">Employer Paid via Subs</div>
            </div>
            <div className="p-3 rounded-xl bg-slate-950/90 border border-slate-800">
              <div className="text-[11px] font-mono text-slate-400">EMPLOYER SHARE / EMPLOYEE</div>
              <div className="text-2xl font-bold font-display text-white">${(grossMonthlyPremiumPerEmployee * 0.60).toFixed(0)}/mo</div>
              <div className="text-[10px] font-mono text-slate-400">$7,020 / employee / yr</div>
            </div>
            <div className="p-3 rounded-xl bg-slate-950/90 border border-slate-800">
              <div className="text-[11px] font-mono text-slate-400">CURRENT SIMULATED COVERAGE</div>
              <div className={`text-2xl font-bold font-display ${coverageRatio >= 100 ? 'text-emerald-400' : 'text-amber-400'}`}>
                {coverageRatio.toFixed(0)}%
              </div>
              <div className="text-[10px] font-mono text-slate-400">
                {coverageRatio >= 100 ? 'Fully Self-Sustaining' : 'Requires Scale'}
              </div>
            </div>
            <div className="p-3 rounded-xl bg-slate-950/90 border border-slate-800">
              <div className="text-[11px] font-mono text-slate-400">MONTHLY HEALTH ESCROW</div>
              <div className="text-2xl font-bold font-display text-[#FF5500]">${totalAllocatedToHealthEscrow.toLocaleString()}/mo</div>
              <div className="text-[10px] font-mono text-slate-400">Dedicated Subs Pool</div>
            </div>
          </div>
        </div>
      </div>

      {/* Interactive Simulation & Allocation Sandbox */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
        {/* Left Side: Sliders & Controls (7 cols) */}
        <div className="lg:col-span-7 rounded-2xl bg-slate-900/90 border-2 border-slate-800 p-6 space-y-6">
          <div className="flex items-center justify-between pb-4 border-b border-slate-800">
            <div>
              <h2 className="text-lg font-display font-bold text-white flex items-center gap-2">
                <Sliders className="w-5 h-5 text-emerald-400" />
                Interactive Headcount & Subscription Scaling Sandbox
              </h2>
              <p className="text-xs text-slate-400 font-mono">
                Adjust team size and active subscriber counts to test the 60% health coverage safety threshold
              </p>
            </div>
            <span className="px-2.5 py-1 rounded bg-slate-950 border border-slate-800 font-mono text-xs text-emerald-400 font-bold">
              Team: {headcount} Staff
            </span>
          </div>

          {/* Headcount Slider */}
          <div className="space-y-2 p-4 rounded-xl bg-slate-950 border border-slate-800">
            <div className="flex items-center justify-between text-xs">
              <label className="font-semibold text-white flex items-center gap-1.5">
                <Users className="w-4 h-4 text-blue-400" />
                Active Team Headcount (2 → 55 Scaling)
              </label>
              <span className="font-mono font-bold text-[#FF5500] text-sm">{headcount} Employees</span>
            </div>
            <input
              type="range"
              min={2}
              max={55}
              step={1}
              value={headcount}
              onChange={(e) => setHeadcount(Number(e.target.value))}
              className="w-full h-2 bg-slate-800 rounded-lg appearance-none cursor-pointer accent-[#FF5500]"
            />
            <div className="flex justify-between text-[10px] font-mono text-slate-500">
              <span>Phase 1 (2-12)</span>
              <span>Phase 2 (13-30)</span>
              <span>Phase 3 (31-55)</span>
            </div>
          </div>

          {/* Subscription Product Sliders */}
          <div className="space-y-4">
            <h3 className="text-xs font-mono uppercase text-slate-400 tracking-wider">
              Live Product Subscription Inflow Streams:
            </h3>

            {/* 1. IAI Survival Guide */}
            <div className="p-3.5 rounded-xl bg-slate-950 border border-slate-800/90 space-y-2">
              <div className="flex items-center justify-between text-xs">
                <div>
                  <span className="font-semibold text-white">1. IAI Survival Guide</span>
                  <span className="ml-2 font-mono text-[11px] text-slate-400">($4/mo • 100% allocated to health)</span>
                </div>
                <div className="text-right font-mono">
                  <div className="text-emerald-400 font-bold">{survivalGuideSubs.toLocaleString()} subs</div>
                  <div className="text-[10px] text-slate-400">${(survivalGuideMRR).toLocaleString()}/mo MRR</div>
                </div>
              </div>
              <input
                type="range"
                min={1000}
                max={65000}
                step={500}
                value={survivalGuideSubs}
                onChange={(e) => setSurvivalGuideSubs(Number(e.target.value))}
                className="w-full h-1.5 bg-slate-800 rounded-lg appearance-none cursor-pointer accent-emerald-400"
              />
            </div>

            {/* 2. IAI Business Manager */}
            <div className="p-3.5 rounded-xl bg-slate-950 border border-slate-800/90 space-y-2">
              <div className="flex items-center justify-between text-xs">
                <div>
                  <span className="font-semibold text-white">2. IAI Business Manager</span>
                  <span className="ml-2 font-mono text-[11px] text-slate-400">($32/mo • 50% allocated to health)</span>
                </div>
                <div className="text-right font-mono">
                  <div className="text-emerald-400 font-bold">{businessManagerSubs.toLocaleString()} subs</div>
                  <div className="text-[10px] text-slate-400">${(businessManagerMRR).toLocaleString()}/mo MRR</div>
                </div>
              </div>
              <input
                type="range"
                min={0}
                max={5000}
                step={50}
                value={businessManagerSubs}
                onChange={(e) => setBusinessManagerSubs(Number(e.target.value))}
                className="w-full h-1.5 bg-slate-800 rounded-lg appearance-none cursor-pointer accent-emerald-400"
              />
            </div>

            {/* 3. DineKey */}
            <div className="p-3.5 rounded-xl bg-slate-950 border border-slate-800/90 space-y-2">
              <div className="flex items-center justify-between text-xs">
                <div>
                  <span className="font-semibold text-white">3. DineKey Medical Credentials</span>
                  <span className="ml-2 font-mono text-[11px] text-slate-400">($28/mo • 40% allocated to health)</span>
                </div>
                <div className="text-right font-mono">
                  <div className="text-emerald-400 font-bold">{dineKeySubs.toLocaleString()} subs</div>
                  <div className="text-[10px] text-slate-400">${(dineKeyMRR).toLocaleString()}/mo MRR</div>
                </div>
              </div>
              <input
                type="range"
                min={100}
                max={15000}
                step={100}
                value={dineKeySubs}
                onChange={(e) => setDineKeySubs(Number(e.target.value))}
                className="w-full h-1.5 bg-slate-800 rounded-lg appearance-none cursor-pointer accent-emerald-400"
              />
            </div>

            {/* 4. Command Suites */}
            <div className="p-3.5 rounded-xl bg-slate-950 border border-slate-800/90 space-y-2">
              <div className="flex items-center justify-between text-xs">
                <div>
                  <span className="font-semibold text-white">4. Command Suites (VDMS/HMDS/UDMS/RDMS)</span>
                  <span className="ml-2 font-mono text-[11px] text-slate-400">($294/mo • 25% allocated to health)</span>
                </div>
                <div className="text-right font-mono">
                  <div className="text-emerald-400 font-bold">{commandSuitesSubs.toLocaleString()} agencies</div>
                  <div className="text-[10px] text-slate-400">${(commandSuitesMRR).toLocaleString()}/mo MRR</div>
                </div>
              </div>
              <input
                type="range"
                min={5}
                max={400}
                step={5}
                value={commandSuitesSubs}
                onChange={(e) => setCommandSuitesSubs(Number(e.target.value))}
                className="w-full h-1.5 bg-slate-800 rounded-lg appearance-none cursor-pointer accent-emerald-400"
              />
            </div>
          </div>
        </div>

        {/* Right Side: Real-Time Balance & Coverage Gauge (5 cols) */}
        <div className="lg:col-span-5 rounded-2xl bg-slate-900/90 border-2 border-slate-800 p-6 space-y-6 flex flex-col justify-between">
          <div>
            <div className="flex items-center justify-between pb-4 border-b border-slate-800">
              <h2 className="text-lg font-display font-bold text-white flex items-center gap-2">
                <PiggyBank className="w-5 h-5 text-[#FF5500]" />
                60% Health Escrow Balance
              </h2>
              <span className="font-mono text-xs text-slate-400">Monthly Run-Rate</span>
            </div>

            {/* Comparison Cards */}
            <div className="space-y-4 pt-4">
              <div className="p-4 rounded-xl bg-slate-950 border border-slate-800 space-y-1">
                <div className="text-xs font-mono text-slate-400 flex items-center justify-between">
                  <span>60% EMPLOYER HEALTH OBLIGATION</span>
                  <span className="text-slate-500">{headcount} × $585/mo</span>
                </div>
                <div className="text-2xl font-bold font-display text-white">
                  ${employer60PercentShare.toLocaleString()} <span className="text-xs font-normal text-slate-400">/ month</span>
                </div>
                <div className="text-[11px] font-mono text-slate-400">
                  Total gross team premium: ${totalMonthlyHealthCostAllEmployees.toLocaleString()}/mo
                </div>
              </div>

              <div className="p-4 rounded-xl bg-slate-950 border-2 border-emerald-500/50 space-y-1">
                <div className="text-xs font-mono text-emerald-400 flex items-center justify-between">
                  <span>SUBSCRIPTION REVENUE ALLOCATED</span>
                  <span>Escrow Inflow</span>
                </div>
                <div className="text-2xl font-bold font-display text-emerald-400">
                  ${totalAllocatedToHealthEscrow.toLocaleString()} <span className="text-xs font-normal text-slate-400">/ month</span>
                </div>
                <div className="text-[11px] font-mono text-slate-300">
                  From ${totalSaaSMRR.toLocaleString()}/mo total SaaS MRR
                </div>
              </div>

              {/* Coverage Ratio Status Box */}
              <div className={`p-4 rounded-xl border ${
                coverageRatio >= 100
                  ? 'bg-emerald-950/40 border-emerald-700/60'
                  : 'bg-amber-950/40 border-amber-700/60'
              }`}>
                <div className="flex items-center justify-between">
                  <span className="text-xs font-mono font-bold uppercase text-white">Coverage Ratio</span>
                  <span className={`text-lg font-black font-display ${coverageRatio >= 100 ? 'text-emerald-400' : 'text-amber-400'}`}>
                    {coverageRatio.toFixed(1)}%
                  </span>
                </div>
                <div className="w-full bg-slate-950 h-2 rounded-full overflow-hidden mt-2 border border-slate-800">
                  <div
                    style={{ width: `${Math.min(coverageRatio, 100)}%` }}
                    className={`h-full ${coverageRatio >= 100 ? 'bg-emerald-400' : 'bg-amber-400'}`}
                  />
                </div>
                <p className="text-[11px] text-slate-300 mt-2">
                  {coverageRatio >= 100 ? (
                    <span className="text-emerald-300 flex items-center gap-1 font-mono">
                      <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400 inline" />
                      100% of the 60% health care mandate is satisfied with a surplus buffer of ${netMonthlyEscrowSurplus.toLocaleString()}/mo!
                    </span>
                  ) : (
                    <span className="text-amber-300 font-mono">
                      Warning: Inflow covers {coverageRatio.toFixed(0)}% of the target. Additional subscription scaling required.
                    </span>
                  )}
                </p>
              </div>
            </div>
          </div>

          <div className="p-3.5 rounded-xl bg-slate-950 border border-slate-800 text-xs text-slate-400 space-y-1">
            <div className="font-semibold text-white flex items-center gap-1.5">
              <Info className="w-4 h-4 text-blue-400" />
              PEO Automated Escrow Architecture
            </div>
            <p className="text-[11px] text-slate-300 leading-relaxed">
              Stripe/Apple subscription payouts automatically route directly into a dedicated Mercury Health Escrow account, which synchronizes with Rippling PEO's Section 125 pre-tax cafeteria plan.
            </p>
          </div>
        </div>
      </div>

      {/* Comprehensive Benefits Package Breakdown */}
      <div className="rounded-2xl bg-slate-900/90 border-2 border-slate-800 p-6 sm:p-8 space-y-6">
        <h2 className="text-xl font-display font-bold text-white flex items-center gap-2">
          <Layers className="w-5 h-5 text-[#FF5500]" />
          Full Identity AI Benefits Architecture & Structure
        </h2>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-5">
          {/* Benefit 1: Medical Insurance */}
          <div className="p-5 rounded-xl bg-slate-950 border border-slate-800 space-y-3">
            <div className="w-8 h-8 rounded-lg bg-emerald-500/15 border border-emerald-500/30 flex items-center justify-center text-emerald-400">
              <HeartHandshake className="w-4 h-4" />
            </div>
            <h3 className="font-display font-bold text-base text-white">Medical Insurance</h3>
            <div className="text-xs font-mono text-emerald-400 font-semibold">60% Employer Subsidy</div>
            <p className="text-xs text-slate-400 leading-relaxed">
              Choice of Blue Shield / Aetna Platinum PPO and High-Deductible Health Plan (HDHP) with an annual $500 employer HSA seed.
            </p>
            <div className="pt-2 border-t border-slate-800/80 text-[11px] font-mono text-slate-400">
              Funded by: <strong className="text-white">App Subscriptions</strong>
            </div>
          </div>

          {/* Benefit 2: Dental & Vision */}
          <div className="p-5 rounded-xl bg-slate-950 border border-slate-800 space-y-3">
            <div className="w-8 h-8 rounded-lg bg-blue-500/15 border border-blue-500/30 flex items-center justify-center text-blue-400">
              <ShieldCheck className="w-4 h-4" />
            </div>
            <h3 className="font-display font-bold text-base text-white">Dental & Vision</h3>
            <div className="text-xs font-mono text-blue-400 font-semibold">60% Employer Subsidy</div>
            <p className="text-xs text-slate-400 leading-relaxed">
              Comprehensive dental (Delta Dental Premier) covering 100% preventive cleanings and VSP Vision covering annual exams + hardware allowance.
            </p>
            <div className="pt-2 border-t border-slate-800/80 text-[11px] font-mono text-slate-400">
              Coverage: <strong className="text-white">Full Family Eligibility</strong>
            </div>
          </div>

          {/* Benefit 3: Safe Harbor 401(k) */}
          <div className="p-5 rounded-xl bg-slate-950 border border-slate-800 space-y-3">
            <div className="w-8 h-8 rounded-lg bg-indigo-500/15 border border-indigo-500/30 flex items-center justify-center text-indigo-400">
              <PiggyBank className="w-4 h-4" />
            </div>
            <h3 className="font-display font-bold text-base text-white">Safe Harbor 401(k)</h3>
            <div className="text-xs font-mono text-indigo-400 font-semibold">4% Direct Match</div>
            <p className="text-xs text-slate-400 leading-relaxed">
              Automated retirement savings via Guideline/Human Interest with 100% match on first 3% and 50% on next 2% (4% total match).
            </p>
            <div className="pt-2 border-t border-slate-800/80 text-[11px] font-mono text-slate-400">
              Vesting: <strong className="text-white">Immediate 100%</strong>
            </div>
          </div>

          {/* Benefit 4: Remote & Hardware Stipends */}
          <div className="p-5 rounded-xl bg-slate-950 border border-slate-800 space-y-3">
            <div className="w-8 h-8 rounded-lg bg-[#FF5500]/15 border border-[#FF5500]/30 flex items-center justify-center text-[#FF5500]">
              <Sparkles className="w-4 h-4" />
            </div>
            <h3 className="font-display font-bold text-base text-white">Workstation & Wellness</h3>
            <div className="text-xs font-mono text-[#FF5500] font-semibold">$1,000 + $150/mo</div>
            <p className="text-xs text-slate-400 leading-relaxed">
              $1,000 one-time home office setup, Apple M-series hardware with MDM security, and $150/mo flexible wellness/learning stipend.
            </p>
            <div className="pt-2 border-t border-slate-800/80 text-[11px] font-mono text-slate-400">
              Security: <strong className="text-white">Hardware YubiKeys</strong>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
